
package Admin;

import javax.swing.table.DefaultTableModel;

public class frmInvoice extends javax.swing.JFrame {
    public frmInvoice() {

        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ecommerce Platforms");
        
    }
    public  void addRowToTheTable(Object[] dataRow) {
        
        DefaultTableModel model = (DefaultTableModel) tableBill.getModel();
        Object[] columns = {"PName", "Quantity", "Price"};
        model.setColumnIdentifiers(columns);
        tableBill.setModel(model);
        model.addRow(dataRow);
        
        int sum = 0;
        for (int i = 0; i < tableBill.getRowCount(); i++) {
            sum = sum + Integer.parseInt(tableBill.getValueAt(i, 2).toString());
        }
        totalPriceLB.setText(Integer.toString(sum));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBill = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalPriceLB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deliFee = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        finalPriceLB = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dateLB = new javax.swing.JLabel();
        oidLB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameLB = new javax.swing.JLabel();
        backLB = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cidInvoiceLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setText("Invoice");

        tableBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableBill);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Sub-total:");

        totalPriceLB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalPriceLB.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Delivery Fee:");

        deliFee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deliFee.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Total:");

        finalPriceLB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finalPriceLB.setText("0");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel6.setText("Order Information:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Transaction Date:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Invoice No. :");

        dateLB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dateLB.setText("date");

        oidLB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oidLB.setText("oid");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Customer Name:");

        nameLB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLB.setText("name");

        backLB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backLB.setText("Back to shopping?");
        backLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLBMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Customer ID:");

        cidInvoiceLB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cidInvoiceLB.setText("cid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalPriceLB)
                    .addComponent(deliFee)
                    .addComponent(totalPriceLB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(backLB)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cidInvoiceLB)
                                    .addComponent(oidLB)
                                    .addComponent(dateLB)
                                    .addComponent(nameLB))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dateLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(oidLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cidInvoiceLB))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalPriceLB)
                    .addComponent(backLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(deliFee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(finalPriceLB))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLBMouseClicked
        this.setVisible(false);
        frmShopping frame = new frmShopping();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        frame.unLB.setText(nameLB.getText());
        frame.cidShopLB.setText(cidInvoiceLB.getText());
    }//GEN-LAST:event_backLBMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLB;
    public javax.swing.JLabel cidInvoiceLB;
    public javax.swing.JLabel dateLB;
    public javax.swing.JLabel deliFee;
    public javax.swing.JLabel finalPriceLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel nameLB;
    public javax.swing.JLabel oidLB;
    private javax.swing.JTable tableBill;
    public javax.swing.JLabel totalPriceLB;
    // End of variables declaration//GEN-END:variables
}
